### ISSUE TITLE
gestPWM.c -> bugs et/ou remarques -> fct GPWM_ExecPWM

### ISSUE THREAD

**Issue by PBYetml** [JoaoManuelMarquesChaves/Tp1_PWM_AD#7]
voir commentaire + lien vidéo sur l'issue #6 

- [ ] => voir #6 => point 2  => gestion de types => librairie
https://github.com/JoaoManuelMarquesChaves/Tp1_PWM_AD/blob/75235377d45aa67c349d07c0c986b3455bcca475/TP1/firmware/src/gestPWM.c#LL106-L107C28
- [ ]  => gestion de types => calculs 
https://github.com/JoaoManuelMarquesChaves/Tp1_PWM_AD/blob/75235377d45aa67c349d07c0c986b3455bcca475/TP1/firmware/src/gestPWM.c#LL134-L134C59
https://github.com/JoaoManuelMarquesChaves/Tp1_PWM_AD/blob/75235377d45aa67c349d07c0c986b3455bcca475/TP1/firmware/src/gestPWM.c#LL141C5-L141C85
https://github.com/JoaoManuelMarquesChaves/Tp1_PWM_AD/blob/75235377d45aa67c349d07c0c986b3455bcca475/TP1/firmware/src/gestPWM.c#LL143C70-L143C70
- [ ] => gestion des définition => librairie 
https://github.com/JoaoManuelMarquesChaves/Tp1_PWM_AD/blob/75235377d45aa67c349d07c0c986b3455bcca475/TP1/firmware/src/gestPWM.c#LL106-L107C28
https://github.com/JoaoManuelMarquesChaves/Tp1_PWM_AD/blob/75235377d45aa67c349d07c0c986b3455bcca475/TP1/firmware/src/gestPWM.c#LL106-L107C28
- [ ] =>  voir #6 => point 1   => gestion des appels de fct => librairie
https://github.com/JoaoManuelMarquesChaves/Tp1_PWM_AD/blob/75235377d45aa67c349d07c0c986b3455bcca475/TP1/firmware/src/gestPWM.c#LL132-L132C45
https://github.com/JoaoManuelMarquesChaves/Tp1_PWM_AD/blob/75235377d45aa67c349d07c0c986b3455bcca475/TP1/firmware/src/gestPWM.c#LL141-L141C85
https://github.com/JoaoManuelMarquesChaves/Tp1_PWM_AD/blob/75235377d45aa67c349d07c0c986b3455bcca475/TP1/firmware/src/gestPWM.c#LL143-L143C70
- [ ] => gestion des appels de fct => paramètres entrée/sortie
https://github.com/JoaoManuelMarquesChaves/Tp1_PWM_AD/blob/75235377d45aa67c349d07c0c986b3455bcca475/TP1/firmware/src/gestPWM.c#LL136C5-L136C64
https://github.com/JoaoManuelMarquesChaves/Tp1_PWM_AD/blob/75235377d45aa67c349d07c0c986b3455bcca475/TP1/firmware/src/gestPWM.c#LL145C2-L145C64

- [ ] => voir https://github.com/Ali-Z0/MINF-TP1-CM-AZ/issues/13 => **similitude entre vos listing (AZR - CME)**
voir la vidéo associé
