### ISSUE TITLE
system_interrupt.c -> bugs et/ou remarques -> ISR -> Timer1

### ISSUE THREAD

**Issue by PBYetml** [JoaoManuelMarquesChaves/Tp1_PWM_AD#9]
voir lien vidéo sur l'issue #6 

- [ ] => voir #8 => gestion de types => librairie
https://github.com/JoaoManuelMarquesChaves/Tp1_PWM_AD/blob/5aa06a985ce150fefc0e3c8ef43ea358a59d79c4/TP1/firmware/src/system_config/default/system_interrupt.c#L79
- [ ] => voir #8 => appel fct => librairie 
https://github.com/JoaoManuelMarquesChaves/Tp1_PWM_AD/blob/5aa06a985ce150fefc0e3c8ef43ea358a59d79c4/TP1/firmware/src/system_config/default/system_interrupt.c#L77
https://github.com/JoaoManuelMarquesChaves/Tp1_PWM_AD/blob/5aa06a985ce150fefc0e3c8ef43ea358a59d79c4/TP1/firmware/src/system_config/default/system_interrupt.c#L84
https://github.com/JoaoManuelMarquesChaves/Tp1_PWM_AD/blob/5aa06a985ce150fefc0e3c8ef43ea358a59d79c4/TP1/firmware/src/system_config/default/system_interrupt.c#L99
- [ ] => **test / condition** => double test => algorithme 
https://github.com/JoaoManuelMarquesChaves/Tp1_PWM_AD/blob/5aa06a985ce150fefc0e3c8ef43ea358a59d79c4/TP1/firmware/src/system_config/default/system_interrupt.c#L81
https://github.com/JoaoManuelMarquesChaves/Tp1_PWM_AD/blob/5aa06a985ce150fefc0e3c8ef43ea358a59d79c4/TP1/firmware/src/system_config/default/system_interrupt.c#L89

- [ ] => **!!! WARNING !!!** => voir [#15](https://github.com/Ali-Z0/MINF-TP1-CM-AZ/issues/15) => listing plus que ressemblant avec  le groupe AZR-CME => même concept d'algorithmie avec les même éléments, c'est rare !!!
https://github.com/Ali-Z0/MINF-TP1-CM-AZ/blob/main/firmware/src/system_config/default/system_interrupt.c
- [ ]
